### ISSUE TITLE
The extension is powered by Vue.js, using Dexie.js with IndexedDB for data persistence

### ISSUE THREAD

**Issue by ozramos** [ozramos/scratchmoar#5]
# Milestones
- [x] Add Vue.js
- [x] Integrate Dexie.js into Vue.js store
- [x] Bootstrap the rest of the Scratchmoar class
